language: go
go:
  - "1.9"
  - "1.10"

before_install:
  # Stuff for Golang
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -covermode=count -coverprofile=profile.cov -v ./...
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
